apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd-prom
  name: nfd-prom-exporter
  namespace: {{ include "icos-nfd.namespace" . }}
spec:
  selector:
    matchLabels:
      app: nfd-prom-exporter
  template:
    metadata:
      labels:
        app: nfd-prom-exporter
    spec:
      containers:
      - args:
        - "apt-get update && apt-get install -y udev && pip install -r /etc/nfd-prom-conf/requirements.txt && python /etc/nfd-prom-conf/prom-exp.py"
        command:
        - /bin/sh
        - -c
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: python:3.9-slim
        name: exporter-container
        securityContext:
          privileged: true
        ports:
        - containerPort: 8081
          name: metrics
        volumeMounts:
        - mountPath: /dev
          name: dev-volume
          readOnly: true
        - mountPath: /etc/nfd-prom-conf
          name: nfd-prom-conf
        - mountPath: /run/udev
          name: udev-db
          readOnly: true
      serviceAccount: nfd-ac
      volumes:
      - configMap:
          name: nfd-prom-conf
        name: nfd-prom-conf
      - name: dev-volume
        hostPath:
          path: /dev
      - name: udev-db
        hostPath:
          path: /run/udev