apiVersion: v1
data:
  prom-exp.py: |
    import os
    import subprocess
    import re
    import requests
    import re
    from prometheus_client import start_http_server, Gauge
    from prometheus_client.core import REGISTRY,GaugeMetricFamily
    import prometheus_client as prom
    import time


    prom.REGISTRY.unregister(prom.PROCESS_COLLECTOR)
    prom.REGISTRY.unregister(prom.PLATFORM_COLLECTOR)
    prom.REGISTRY.unregister(prom.GC_COLLECTOR)

    API_SERVER="https://kubernetes.default.svc"
    SERVICEACCOUNT="/var/run/secrets/kubernetes.io/serviceaccount"
    TOKEN_PATH="{}/token".format(SERVICEACCOUNT)
    CACERT_PATH="{}/ca.crt".format(SERVICEACCOUNT)


    TOKEN_FILE=open(TOKEN_PATH, "r")
    TOKEN=TOKEN_FILE.read()

    NodeName=os.environ.get('NODE_NAME')


    device_patterns = [
        r'^video[0-9]*$',
        r'^ttyUSB[0-9]*$',
        r'^ttyACM[0-9]*$'
    ]

    headers = {
      'Authorization': 'Bearer {}'.format(TOKEN)
    }
 
    custom_registry = prom.CollectorRegistry()

    metric_gauge = Gauge(
      'node_mounted',
      'devices mounted',
      ['node_name','node_uid','device','resource_path'],
      registry=custom_registry
    )


    def query_api(api_url, method="GET", data=None):
      if method == "GET":
          r = requests.get(
              api_url,
              verify=CACERT_PATH,
              headers=headers
          )
      elif method == "POST":
          r = requests.post(
              api_url,
              json=data,
              verify=CACERT_PATH,
              headers=headers
          )
      elif method == "DELETE":
          r = requests.delete(
              api_url,
              verify=CACERT_PATH,
              headers=headers
          )
      return r

    def extract_number(device_path):
        match = re.search(r'(\d+)$', device_path)
        if match:
            return int(match.group(1))
        return 0

    class DeviceCollector(object):
        def __init__(self):
            self.NodeName = NodeName
            pass
            
        def collect(self):

            devices_metrics = self._get_device_metrics()
            
            gauge_family = GaugeMetricFamily(
                'node_mounted',
                'devices mounted',
                labels=['node_name', 'node_uid', 'device', 'resource_path']
            )
            

            for device_id, value in devices_metrics.items():
                node_name, node_uid, device, resource_path = device_id
                gauge_family.add_metric([node_name, node_uid, device, resource_path], value)
                
            yield gauge_family

        def _get_device_metrics(self):
            device_metrics = {}

            api_url = f"{API_SERVER}/api/v1/nodes/{NodeName}"
            resources_url = f'{API_SERVER}/api/v1/pods?fieldSelector=spec.nodeName={NodeName}'

            response = query_api(resources_url)
            node_data = response.json()

            response = query_api(api_url)

            node = response.json()
            node_uid = node['metadata']['uid']

            alloc_devices = list(node['status']['allocatable'].keys())
            filtered_list = [item for item in alloc_devices if item.startswith('icos.eu/')]
            custom_resources = [item for item in filtered_list]

            resource_dict = {}
            for custom_resource in custom_resources:
                resource_dict[custom_resource] = 1

            device_dict = {item.replace('icos.eu/', '/dev/'): item for item in filtered_list}

            for pod in node_data.get("items", []):
                for container in pod["spec"].get("containers", []):
                    resources = container.get("resources", {})
                    if 'requests' in resources:
                        for r in resources['requests'].keys():
                            resource_dict[r] = 0

            unique_devices = []
            video_devices = []
            other_devices = []
            for p in ['/dev']:
                

                try:
                    dev_entries = os.listdir(p)
                except Exception as e:
                    print(f"Error accessing {p}: {e}")
                    dev_entries = []

                for entry in dev_entries:
                    dev_path = os.path.join(p, entry)

                    for pattern in device_patterns:
                        if re.match(pattern, entry):
                            if("video" in entry):
                                video_devices.append(entry)
                            else:
                                other_devices(entry)

            video_devices = sorted(video_devices, key=extract_number)                    
            all_devices = video_devices + other_devices
            for dev_path in all_devices:
                try:
                    id_model = None
                    id_model_id = None
                    id_vendor_id = None
                    id_usb_interface = None
                    cmd = ["udevadm", "info", "--query=all", "--name=" + dev_path]
                    result = subprocess.run(cmd, capture_output=True, text=True)
                    udev_info = result.stdout
                    for line in udev_info.splitlines():
                        if "ID_MODEL=" in line:
                            id_model = line.split('=')[1].strip().strip('"')
                        elif "ID_MODEL_ID=" in line:
                            id_model_id = line.split('=')[1].strip().strip('"')
                        elif "ID_VENDOR_ID=" in line:
                            id_vendor_id = line.split('=')[1].strip().strip('"')
                        elif "ID_USB_INTERFACES=" in line:
                            id_usb_interface = line.split('=')[1].strip().strip('"')

                    
                    if(id_usb_interface == None):
                        continue


                    device_key = f"{id_vendor_id}:{id_model_id}{id_usb_interface}"


                    if device_key in unique_devices:
                        continue
                    else:
                        unique_devices.append(device_key)



                    if "/dev/"+dev_path in device_dict:
                        device_id = (NodeName, node_uid, id_model, device_dict["/dev/"+dev_path])
                        device_metrics[device_id] = resource_dict.get(device_dict["/dev/"+dev_path], 0)
                except Exception as e:
                    print(f"Error processing device {dev_path}: {e}")
            
            return device_metrics




    if __name__ == '__main__':
        device_collector = DeviceCollector()
        prom.REGISTRY.register(device_collector)
        
        start_http_server(8081)
        
        while True:
            time.sleep(5)




  requirements.txt: |-
    prometheus-client
    requests
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nfd-prom-conf
  namespace: {{ .Release.Namespace }}
