apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - prom-exp.py=prom-exp.py
  - requirements.txt=requirements.txt
  name: nfd-prom-conf
